### ISSUE TITLE
LlamaForCausalLM.forward() got an unexpected keyword argument 'seqlens_in_batch'

### ISSUE THREAD

**Issue by Xiaolong-RRL** [NVlabs/VILA-archive#16]
Dear author:

thanks for your great work, but when I finetune vila-3b model, an error happened:
```
  File "/home/xxx/projects/vila/llava/model/language_model/llava_llama.py", line 133, in forward
    outputs = self.llm.forward(
TypeError: LlamaForCausalLM.forward() got an unexpected keyword argument 'seqlens_in_batch'
```
There seems to be something wrong with the code [here](https://github.com/NVlabs/VILA/blob/main/llava/model/language_model/llava_llama.py#L144)

Could you explain the role of the ```seqlens_in_batch``` parameter, and how to fix this error?

**Comment by yaolug** [comment]
Could you let me know how you finetune VILA-3B model?

So the reason why we use `seqlens_in_batch` is because 
1. we did example packing, so that each row may contain multiple examples
2. and we need to tell flashattention the length of each example in a row

The example packing will speed up training by 2x.
If your dataset is small, you can try to disable the example packing. You can remove that parameter in your code.
We get `seqlens_in_batch` to work by replacing some files in huggingface transformer. 
See last line of the install instruction https://github.com/NVlabs/VILA?tab=readme-ov-file#installation

**Comment by dragen1860** [comment]
@yaolug hi， how to ` disable the example packing. You can remove that parameter in your code.`?

**Comment by Lyken17** [comment]
Hi there,

Our team has moved our VILA to a new location: [NVLabs/VILA](https://github.com/NVlabs/VILA). We kindly request that you update your references to the old repository location with the new one (e.g, git clone / pipeline integration). This will ensure that you have access to the latest updates, improvements, and bug fixes for VILA project. Current repo will be archieved in one week (Jul 10th) and made private after one month (Aug 4th).

Thank you for your understanding and continued support. If your issue still exists, feel free to open a new one in the new place. We appreciate your patience and cooperation during this transition.

Best regards,
VILA Team

**Comment by Efficient-Large-Language-Model** [comment]
@dragen1860 
Yes.
