### ISSUE TITLE
got valueError when running Llama-3-VILA1.5-8B inference

### ISSUE THREAD

**Issue by QuickSolverDab** [NVlabs/VILA-archive#22]
Hello,
I ran the inference code you provided, but I received a ValueError.
Errors occurred in both run_vila.py and inference_test.py, and the message is as follows.

`Traceback (most recent call last):
  File "/home/VILA/./inference_test/inference_test.py", line 148, in <module>
    result_list = eval_model(args, model, tokenizer, image_processor)
  File "/home/VILA/./inference_test/inference_test.py", line 57, in eval_model
    image_tensor = process_images(image_list, image_processor, model.config)
  File "/home/VILA/llava/mm_utils.py", line 198, in process_images
    new_images = [process_image(image, model_cfg, None) for image in images]
  File "/home/VILA/llava/mm_utils.py", line 198, in <listcomp>
    new_images = [process_image(image, model_cfg, None) for image in images]
  File "/home/VILA/llava/mm_utils.py", line 192, in process_image
    image = processor.preprocess(image, return_tensors="pt")["pixel_values"][0]
  File "/home/VILA/llava/model/multimodal_encoder/siglip/image_processing_siglip.py", line 302, in preprocess
    return BatchFeature(data=data, tensor_type=return_tensors)
  File "/home/VILA/venv/lib/python3.10/site-packages/transformers/feature_extraction_utils.py", line 78, in __init__
    self.convert_to_tensors(tensor_type=tensor_type)
  File "/home/VILA/venv/lib/python3.10/site-packages/transformers/feature_extraction_utils.py", line 188, in convert_to_tensors
    raise ValueError(
ValueError: Unable to create tensor, you should probably activate padding with 'padding=True' to have batched tensors with the same length.`

Thank you.

**Comment by yaolug** [comment]
Did you use `--conv-mode=llama_3` ?

**Comment by QuickSolverDab** [comment]
Yes I did,

**Comment by osttkm** [comment]
Hello, I had a same problem.

**Comment by yaolug** [comment]
Could you provide your full command line? Are you testing w/ image or video?

**Comment by osttkm** [comment]
Thank you very much for your response. 
I tried two demo scripts with an image, but both of them have the same error.

python ./inference_test.py \
    --model-name Efficient-Large-Model/Llama-3-VILA1.5-8b \
    --conv-mode llama_3 \
    --test_image_path ./test_data \
    --test_json_path ./inference_test_sub.json \
    --pad
※Json file has only pizza.png.

python llava/eval/run_vila.py \
    --model-path Efficient-Large-Model/Llama-3-VILA1.5-8b \
    --conv-mode llama_3 \
    --query "<image>\n Please describe the traffic condition." \
    --image-file "demo_images/av.png"

**Comment by osttkm** [comment]
I found a solution.
The problem was occurring when trying to convert images (numpy.float32) to tensors in transformers/feature_extraction_utils.py, causing a conversion error.
By pre-converting the images to tensors in multimodal_encoder/sidlip/image_processing_siglip.py before passing them to BatchFeature, like so:
`images = torch.tensor(images, dtype=torch.float32)`
I was able to avoid the error. Although I haven't tested this with multiple images, the same process should likely work.

**Comment by tongzhoumu** [comment]
Downgrading numpy to 1.26 solves the issue for me.

**Comment by Lyken17** [comment]
Hi there,

Our team has moved our VILA to a new location: [NVLabs/VILA](https://github.com/NVlabs/VILA). We kindly request that you update your references to the old repository location with the new one (e.g, git clone / pipeline integration). This will ensure that you have access to the latest updates, improvements, and bug fixes for VILA project. Current repo will be archieved in one week (Jul 10th) and made private after one month (Aug 4th).

Thank you for your understanding and continued support. If your issue still exists, feel free to open a new one in the new place. We appreciate your patience and cooperation during this transition.

Best regards,
VILA Team

**Comment by osttkm** [comment]
Thanks @tongzhoumu 
I'll tyr it.

I found an another solution by myself.
The problem was occurring when trying to convert images (numpy.float32) to tensors in transformers/feature_extraction_utils.py, causing a conversion error.
By pre-converting the images to tensors in multimodal_encoder/sidlip/image_processing_siglip.py before passing them to BatchFeature, like so:
`images = torch.tensor(images, dtype=torch.float32)`
I was able to avoid the error. Although I haven't tested this with multiple images, the same process should likely work.

@Lyken17 Thank you for your consideration.
